config/routes.rb
Rhea::Engine.routes.draw do
  get '/', to: 'commands#index', as: 'rhea'
  resources :commands, only: [:index, :create] do
    collection do
      get :delete
      get :export
      get :redeploy
      get :reschedule
      get :stop
      post :batch_update
      put :import
    end
  end
  resources :events, only: [:index]
  resources :nodes, only: [:index]
  resources :system_services, only: [:index]

  namespace 'api' do
    get '/jobs', to: 'jobs#index'
  end
end

app/controllers/rhea/base_controller.rb
module Rhea
  class BaseController < ActionController::Base
    protect_from_forgery

    layout 'rhea/layouts/application'

    helper Rhea::Helper

    around_filter :rescue_exceptions

    private

    def rescue_exceptions
      yield
    rescue Errno::ECONNREFUSED
      render_connection_exception
    rescue Rhea::Kubernetes::ServerError => e
      flash[:alert] = e.message
      render_connection_exception
    end

    def render_connection_exception
      render 'rhea/errors/index'
    end
  end
end

app/controllers/rhea/commands_controller.rb
module Rhea
  class CommandsController < Rhea::BaseController
    def index
      @commands = Rhea::Kubernetes::Commands::All.new.perform
      @default_image = Rhea.configuration.default_image
      @images = (@commands.map(&:image) + [@default_image]).uniq.sort
      if params[:image].present?
        @commands = @commands.select { |command| command.image == params[:image] }
      end
    end

    def create
      command_type_key = params[:command_type_key].presence
      command_type_input = params[:command_type_input]
      process_count = params[:process_count].presence.try(:to_i) || 1
      image = params[:image].presence

      redirect_to :back, flash: { error: 'Blank command_type_key' } and return if command_type_key.blank?
      redirect_to :back, flash: { error: 'Blank process_count' } and return if process_count.blank?
      redirect_to :back, flash: { error: 'Blank image' } and return if image.blank?

      command_type = Rhea::CommandType.find(command_type_key)
      command_expression = command_type.input_to_command_expression(command_type_input)

      Rhea::Kubernetes::Commands::Scale.new(expression: command_expression, image: image, process_count: process_count).perform
      wait_for_updates_to_persist
      redirect_to params[:redirect_to], notice: 'Command created!'
    end

    def batch_update
      case params[:batch_action]
      when 'redeploy'
        batch_redeploy
      when 'reschedule'
        batch_reschedule
      when 'scale'
        batch_scale
      when 'stop'
        batch_stop
      else
        redirect_to params[:redirect_to], notice: 'Invalid action!'
      end
    end

    def delete
      command_attributes = image_expression_to_command_attributes(params[:image_expression])
      Rhea::Kubernetes::Commands::Delete.new(command_attributes).perform
      flash[:notice] = "Command '#{command_attributes[:expression]}' deleted!"
      redirect_to :back
    end

    def export
      data = Rhea::Kubernetes::Commands::Export.new.perform
      respond_to do |format|
        format.json { send_data data.to_json, type: :json, disposition: 'attachment', filename: 'rhea.json' }
      end
    end

    def import
      data = ActiveSupport::JSON.decode(params[:data].read)
      commands = data['commands']
      if commands.nil?
        flash[:alert] = 'Invalid file'
        redirect_to :back
        return
      end

      Rhea::Kubernetes::Commands::Import.new(data).perform
      flash[:notice] = "Imported #{commands.length} commands!"
      redirect_to :back
    end

    def redeploy
      command_attributes = image_expression_to_command_attributes(params[:image_expression])
      Rhea::Kubernetes::Commands::Redeploy.new(command_attributes).perform
      flash[:notice] = "Command '#{command_attributes[:expression]}' redeployed!"
      redirect_to :back
    end

    def reschedule
      command_attributes = image_expression_to_command_attributes(params[:image_expression])
      Rhea::Kubernetes::Commands::Reschedule.new(command_attributes).perform
      flash[:notice] = "Command '#{command_attributes[:expression]}' rescheduled!"
      redirect_to :back
    end

    def stop
      command_attributes = image_expression_to_command_attributes(params[:image_expression])
      Rhea::Kubernetes::Commands::Scale.new(command_attributes.merge(process_count: 0)).perform
      flash[:notice] = "Command '#{command_attributes[:expression]}' stopped!"
      redirect_to :back
    end

    private

    def batch_redeploy
      image_expressions = params[:batch_image_expressions]
      redirect_to params[:redirect_to], notice: 'No commands were selected!' and return if image_expressions.blank?
      threads = image_expressions.map do |image_expression|
        command_attributes = image_expression_to_command_attributes(image_expression)
        Thread.new do
          Rhea::Kubernetes::Commands::Redeploy.new(command_attributes).perform
        end
      end
      threads.map(&:join)
      wait_for_updates_to_persist
      redirect_to params[:redirect_to], notice: "Redeployed #{image_expressions.length} #{'command'.pluralize(image_expressions.length)}!"
    end

    def batch_reschedule
      image_expressions = params[:batch_image_expressions]
      redirect_to params[:redirect_to], notice: 'No commands were selected!' and return if image_expressions.blank?
      threads = image_expressions.map do |image_expression|
        command_attributes = image_expression_to_command_attributes(image_expression)
        Thread.new do
          Rhea::Kubernetes::Commands::Reschedule.new(command_attributes).perform
        end
      end
      threads.map(&:join)
      wait_for_updates_to_persist
      redirect_to params[:redirect_to], notice: "Rescheduled #{image_expressions.length} #{'command'.pluralize(image_expressions.length)}!"
    end

    def batch_scale
      image_expressions_process_counts = params[:image_expressions_process_counts]
      scaled_commands_count = 0
      image_expressions_process_counts.each do |image_expression, process_count|
        next if process_count.blank?
        process_count = process_count.to_i
        command_attributes = image_expression_to_command_attributes(image_expression)
        Rhea::Kubernetes::Commands::Scale.new(command_attributes.merge(process_count: process_count)).perform
        scaled_commands_count += 1
      end
      wait_for_updates_to_persist
      redirect_to params[:redirect_to], notice: "Scaled #{scaled_commands_count} #{'command'.pluralize(scaled_commands_count)}!"
    end

    def batch_stop
      image_expressions = params[:batch_image_expressions]
      redirect_to params[:redirect_to], notice: 'No commands were selected!' and return if image_expressions.blank?
      threads = image_expressions.map do |image_expression|
        command_attributes = image_expression_to_command_attributes(image_expression)
        Thread.new do
          Rhea::Kubernetes::Commands::Scale.new(command_attributes.merge(process_count: 0)).perform
        end
      end
      threads.map(&:join)
      wait_for_updates_to_persist
      redirect_to params[:redirect_to], notice: "Stopped #{image_expressions.length} #{'command'.pluralize(image_expressions.length)}!"
    end

    # Sleep briefly to prevent user needing to refresh the page to see updated counts
    def wait_for_updates_to_persist
      sleep 0.2
    end

    # TODO: Use proper form submissions instead of string concatenation
    def image_expression_to_command_attributes(image_expression)
      image_expression = CGI.unescape(image_expression)
      image, expression = image_expression.split(Rhea::Command::IMAGE_EXPRESSION_SEPARATOR, 2)
      {
        image: image,
        expression: expression
      }
    end
  end
end

app/controllers/rhea/events_controller.rb
module Rhea
  class EventsController < Rhea::BaseController
    def index
      events = Rhea::Kubernetes::Events::Recent.new.perform
      @events = Kaminari.paginate_array(events).page(params[:page]).per(200)
    end
  end
end

app/controllers/rhea/nodes_controller.rb
module Rhea
  class NodesController < Rhea::BaseController
    def index
      @nodes = Rhea::Kubernetes::Nodes::All.new.perform
    end
  end
end

app/controllers/rhea/system_services_controller.rb
module Rhea
  class SystemServicesController < Rhea::BaseController
    def index
      @service_names_urls = Rhea::Kubernetes::SystemServices.service_names_urls
    end
  end
end

app/controllers/rhea/workers_controller.rb
module Rhea
  class WorkersController < Rhea::BaseController
    def index
      @commands_workers_counts = Rhea::Kubernetes::Worker.commands_workers_counts
    end

    def delete
      command = params[:command]
      command = CGI.unescape(command)
      Rhea::Kubernetes::Worker.destroy(command)
      flash[:notice] = "Command '#{command}' deleted"
      redirect_to :back
    end

    def update_all
      # TODO: Don't scale unless necessary
      commands_worker_counts = params[:commands_worker_counts]
      commands_worker_counts.each do |command, worker_count|
        next if worker_count.blank?
        worker_count = worker_count.to_i
        begin
          Rhea::Kubernetes::Worker.scale(command, worker_count)
          # Sleep briefly to prevent user needing to refresh page to see updated count
          sleep 0.2
        rescue Rhea::Kubernetes::ServerError => e
          flash[:alert] = e.message
          redirect_to :back and return
        end
      end
      redirect_to params[:redirect_to], notice: 'Saved!'
    end

    def start
      command_type_key = params[:command_type_key].presence
      command_type_input = params[:command_type_input].presence
      workers_count = params[:workers_count].presence

      redirect_to :back, flash: { error: 'Blank command_type_key' } and return if command_type_key.blank?
      redirect_to :back, flash: { error: 'Blank command_type_input' } and return if command_type_input.blank?
      redirect_to :back, flash: { error: 'Blank workers_count' } and return if workers_count.blank?

      command_type = Rhea::CommandType.find(command_type_key)
      command = command_type.input_to_command(command_type_input)

      Rhea::Kubernetes::Worker.scale(command, workers_count.to_i)
      # Sleep briefly to prevent user needing to refresh page to see updated counts
      sleep 0.1
      redirect_to params[:redirect_to], notice: 'Started!'
    end
  end
end

app/helpers/rhea/helper.rb
module Rhea
  module Helper
    def app_name
      'Rhea'
    end

    def root_path
      Rhea.root_path
    end

    def humanize_image(image)
      image.split('/').last
    end

    ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

    def bootstrap_flash(options = {})
      flash_messages = []
      flash.each do |type, message|
        # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
        next if message.blank?

        type = type.to_sym
        type = :success if type == :notice
        type = :danger  if type == :alert
        type = :danger  if type == :error
        next unless ALERT_TYPES.include?(type)

        tag_class = options.extract!(:class)[:class]
        tag_options = {
          class: "alert fade in alert-#{type} #{tag_class}"
        }.merge(options)

        Array(message).each do |msg|
          text = content_tag(:div, msg.html_safe, tag_options)
          flash_messages << text if msg
        end
      end
      flash_messages.join("\n").html_safe
    end

    IMAGE_ID_REGEX = /^docker:\/\/sha256:([a-z0-9]+)/.freeze
    def humanize_image_id(image_id)
      IMAGE_ID_REGEX.match(image_id).try(:[], 1).try(:first, 12)
    end
  end
end

app/views/rhea/commands/_form.html.haml
= form_tag commands_path, method: 'POST', class: 'form-horizontal' do
  = hidden_field_tag :redirect_to, request.fullpath
  .form-group
    = label_tag :image, 'Image', class: 'col-sm-3 control-label'
    .col-sm-9
      = text_field_tag :image, Rhea.configuration.default_image, class: 'form-control', style: 'width: 100%;', placeholder: Rhea.configuration.default_image
  .form-group
    = label_tag :command_type_key, 'Type', class: 'col-sm-3 control-label'
    .col-sm-9
      = select_tag :command_type_key, options_for_select(Rhea::CommandType.options_for_select, Rhea.configuration.default_command_type_key), class: 'form-control', style: 'width: 90px;', required: 'required'
  .form-group
    = label_tag :command_syntax, 'Command', class: 'col-sm-3 control-label', style: 'font-weight: normal;'
    .col-sm-9
      %pre.command-syntax{style: 'font-size: 12px;'}
        = Rhea::CommandType.find(Rhea.configuration.default_command_type_key).displayed_format
  .form-group
    = label_tag :command_type_input, '$input', class: 'col-sm-3 control-label'
    .col-sm-9
      = text_field_tag :command_type_input, nil, class: 'form-control', style: 'width: 100%;'
  .form-group
    = label_tag :process_count, 'Processes', class: 'col-sm-3 control-label'
    .col-sm-9
      = text_field_tag :process_count, 1, class: 'form-control', style: 'width: 50px;', placeholder: 1
  .form-group
    .col-sm-3
    .col-sm-9
      = submit_tag 'Create', class: 'btn btn-success'

app/views/rhea/commands/_table.html.haml
%table.table.table-condensed.table-striped
  %thead
    %tr
      %th{style: 'width: 25px;'}
        %input{type: 'checkbox', id: 'check-all'}
      %th Image
      %th Command
      %th Processes
      %th Desired Processes
      %th Deployed
      %th
  %tbody
    - commands.each do |command|
      - escaped_image_expression = CGI.escape([command.image, command.expression].join(Rhea::Command::IMAGE_EXPRESSION_SEPARATOR))
      %tr
        %td
          = check_box_tag 'batch_image_expressions[]', escaped_image_expression, false, class: 'command-checkbox checkbox'
        %td= humanize_image(command.image)
        %td= command.expression
        %td= command.process_count
        %td
          = text_field_tag "image_expressions_process_counts[#{escaped_image_expression}]", nil, class: 'form-control', style: 'width: 50px;'
        %td
          %small.text-muted
            = time_ago_in_words(command.created_at.in_time_zone(Time.zone), include_seconds: true)
            ago
        %td{ style: 'white-space: nowrap;' }
          = link_to redeploy_commands_path(image_expression: escaped_image_expression), title: 'Redeploy', class: 'btn btn-primary btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
            %span.glyphicon.glyphicon-cloud-download
          = link_to reschedule_commands_path(image_expression: escaped_image_expression), title: 'Reschedule', class: 'btn btn-primary btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
            %span.glyphicon.glyphicon-fullscreen
          - if command.process_count == 0
            = link_to delete_commands_path(image_expression: escaped_image_expression), title: 'Delete', class: 'btn btn-danger btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
              %span.glyphicon.glyphicon-remove
          - else
            = link_to stop_commands_path(image_expression: escaped_image_expression), title: 'Stop', class: 'btn btn-warning btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
              %span.glyphicon.glyphicon-stop
    %tr
      %td{ colspan: 2 }
        .batch-actions{ style: 'display: none;' }
          = button_tag name: 'batch_action', value: 'redeploy', title: 'Redeploy', class: 'btn btn-primary btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
            %span.glyphicon.glyphicon-cloud-download
          = button_tag name: 'batch_action', value: 'reschedule', title: 'Reschedule', class: 'btn btn-primary btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
            %span.glyphicon.glyphicon-fullscreen
          = button_tag name: 'batch_action', value: 'stop', title: 'Stop', class: 'btn btn-warning btn-xs btn-action', 'data-toggle': 'tooltip', 'data-placement': 'bottom' do
            %span.glyphicon.glyphicon-stop
      %td
      %td
      %td
        = button_tag 'Save', name: 'batch_action', value: 'scale', class: 'btn btn-success'
      %td
      %td

app/views/rhea/commands/index.html.haml
.row
  .col-md-8
    .row
      .col-md-12
        .pull-left
          = form_tag commands_path, method: 'GET', class: 'form-inline' do
            .form-group
              = label_tag :image, 'Image', style: 'margin-right: 5px; font-size: 13px;'
              - image_options = [['All', nil]] + @images.map { |image| [humanize_image(image), image] }
              = select_tag :image, options_for_select(image_options, params[:image].presence), class: 'form-control', onchange: "$(this).closest('form').submit();"
        .pull-right
          = form_tag import_commands_path, method: 'PUT', multipart: true, style: 'display: inline-block;' do
            %span.btn.btn-default.btn-file
              Import
              = file_field_tag :data, accept: 'application/json', onchange: "$(this).closest('form').submit();"
          = link_to 'Export', export_commands_path(format: 'json'), class: 'btn btn-default'
        %br
        %br
        %br
    .row
      .col-md-12
        - if @commands.present?
          = form_tag batch_update_commands_path, method: 'POST' do
            = hidden_field_tag :redirect_to, request.fullpath
            = render partial: 'rhea/commands/table', locals: { commands: @commands }
        - else
          %p
            No commands found.

  .col-md-4
    .panel.panel-default
      .panel-heading
        %h4 New Command
      .panel-body
        = render partial: 'rhea/commands/form'

:javascript
  var checkboxes = $('.command-checkbox');
  var batchActions = $('.batch-actions');

  var toggleBatchActions = function() {
    batchActions.toggle(checkboxes.filter(':checked').length > 0);
    return true;
  };

  var updateCommandSyntax = function() {
    var syntax = this.selectedOptions[0].dataset.syntax;
    $('.command-syntax').text(syntax);
  };

  checkboxes.on('click', toggleBatchActions);

  $('#check-all').change(function(){
    $(".command-checkbox").prop('checked', $(this).prop("checked"));
    toggleBatchActions()
  });

  $('#command_type_key').on('change', updateCommandSyntax);